### ISSUE TITLE
好想学习一下GM(1,N)预测部分代码

### ISSUE THREAD

**Issue by webelieveagain** [Timecollector/Grey_Model#1]
想用来做一个腐蚀预测相关的

**Comment by Timecollector** [comment]
你好，已经更新了相关的代码，你可以看一下

**Comment by webelieveagain** [comment]
谢谢好兄弟啊，现在遇到个问题，我是四个相关因素，输入18组数据，但是最多只能往下预测16年。这个向下预测的上限是根据输入数据组数变化的吗/

**Comment by Timecollector** [comment]
因为需要用到相关因素，所以你给了多少期相关因素，就能预测多少期，不过灰色预测模型更适合短期预测，长期预测可能会出现极大的误差

**Comment by webelieveagain** [comment]
可以修改为无限制往下预测吗？误差太大也没事。尝试了一下总是报错

**Comment by Timecollector** [comment]
报的啥错啊，复制一下我看看

**Comment by webelieveagain** [comment]
----这是我的输入数据，是读取excel文件内容的。
腐蚀速率（mm/a)	CO2分压( ＭPa ）	H2S分压（Mpa)	温度(k）	流速(m/s)
0.149783544	0.1	0.001	308.15	1.5
0.16489477	0.2	0.002	308.15	2
0.199912997	0.3	0.003	308.15	2.5
0.181681515	0.1	0.002	318.15	2.5
0.209126068	0.2	0.003	318.15	1.5
0.165095266	0.3	0.001	318.15	2
0.230333323	0.1	0.003	328.15	2
0.180900371	0.2	0.001	328.15	2.5
0.188479374	0.3	0.002	328.15	1.5
0.17484241	0.1	0.001	328.15	1.5
0.192481752	0.2	0.002	328.15	2
0.233358548	0.3	0.003	328.15	2.5
0.181681515	0.1	0.002	318.15	2.5
0.209126068	0.2	0.003	318.15	1.5
0.165095266	0.3	0.001	318.15	2
0.197321356	0.1	0.003	308.15	2
0.154973262	0.2	0.001	308.15	2.5
0.161466023	0.3	0.002	308.15	1.5


后四列为相关因素输入。
前16年都可以正常预测。

当预测第17年时候，出现如下报错：
Traceback (most recent call last):
  File "D:/迅雷下载/GM1N/gm1n.py", line 118, in cum
    fit_values = model.fit()
  File "D:/迅雷下载/GM1N/gm1n.py", line 53, in fit
    self.__lsm()
  File "D:/迅雷下载/GM1N/gm1n.py", line 50, in __lsm
    self.coff = np.matmul(np.linalg.inv(np.matmul(B.T, B)), np.matmul(B.T, Y))
  File "<__array_function__ internals>", line 180, in inv
  File "C:\Users\pillar\AppData\Roaming\Python\Python38\site-packages\numpy\linalg\linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "C:\Users\pillar\AppData\Roaming\Python\Python38\site-packages\numpy\linalg\linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

当预测18年及以后的时候，出现一下报错：
Traceback (most recent call last):
  File "D:/迅雷下载/GM1N/gm1n.py", line 118, in cum
    fit_values = model.fit()
  File "D:/迅雷下载/GM1N/gm1n.py", line 53, in fit
    self.__lsm()
  File "D:/迅雷下载/GM1N/gm1n.py", line 41, in __lsm
    Z = np.zeros((self.data_shape - 1, 1))
ValueError: negative dimensions are not allowed

**Comment by Timecollector** [comment]
第一个问题是在最小二乘的时候出现了奇异矩阵，导致了矩阵不可逆，这个没有特别好的解决办法，只能通过更换数据等等方法
第二个问题是维度问题，你的相关影响因素CO2分压( ＭPa ）、H2S分压（Mpa) 、温度(k）、流速(m/s)只有17期，要预测第18期的腐蚀速率你需要在excel表最后一行给定CO2分压( ＭPa ）、H2S分压（Mpa) 、温度(k）、流速(m/s)这几个因素第18期的值，然后设置预测步长为1，这样就可以通过前面17期数据建模，预测第18期数据。
CO2分压( ＭPa ）、H2S分压（Mpa) 、温度(k）、流速(m/s)这几个数据可以通过GM(1,1)模型预测第18期数据，然后输入到excel表中

**Comment by webelieveagain** [comment]
大致明白了好兄弟。想恳请好兄弟推荐有一些学习GM(1,1)、GM(1,n)的学习资料，比如视频、书籍、文档博客。相关教学我在B站没有找到太多有关于PYTHON的灰色模型讲解，我又对Matlab完全不懂。

**Comment by Timecollector** [comment]
感觉灰色系统方向大多都是用的matlab，python相关的资料会比较少。如果你感兴趣的话可以看看b站上刘思峰老师的灰色系统课程，但是python代码的话就需要理解模型之后自己写了

**Comment by webelieveagain** [comment]
嗯嗯，谢谢
