### ISSUE TITLE
gm(1,n)预测值疑问

### ISSUE THREAD

**Issue by hihiworld** [Timecollector/Grey_Model#2]
楼主，小白求教，我运行你的代码结果如下
fit_values：[20556.0, 8288.479987319675, 11105.662939219459, 13364.70443357066, 15010.55616216264, 18024.062450851052]
predict_values：[51233.43876822575, 73618.88341107947, 92433.72966214709]

这个predict_values应该是未来三期的预测值，可是明显不是递增，这是为何？
另请问fit_values是指过去六期的拟合值吗？这个为何跟原值不同？
感谢楼主答疑

我把自己的数据带入，结果fit_values出现负值，这是为何？

**Comment by Timecollector** [comment]
请问一下你预测的时候用的是离散的方式还是连续的方式啊

**Comment by hihiworld** [comment]
> 请问一下你预测的时候用的是离散的方式还是连续的方式啊

是连续值，数据结构和您所用案例基本一致，请问运行示例代码读取power.xls为何预测三期的predict value不是递增？而且和gm11差的有点大。

**Comment by Timecollector** [comment]
GM(1,N)连续的情况可能会有比较大的误差。
power.xlsx中的数据是周期变化的，GM(1,1)是预测不了这种周期性的，虽然GM(1,N)预测周期序列会有比较大的误差，但是一定程度上可以反映出周期变化趋势。如果想预测周期序列，可以使用GM(1,1|sin）模型

**Comment by hihiworld** [comment]
多谢楼主解答，感谢
