### ISSUE TITLE
大佬好 测试数据可以提供么

### ISSUE THREAD

**Issue by yauso1** [Timecollector/Grey_Model#3]
GM11.py中test.xlsx可以提供下么

**Comment by Timecollector** [comment]
已经上传了，https://github.com/Timecollector/Grey_Model/blob/main/test.xlsx

**Comment by yauso1** [comment]
非常感谢！
















在 2022-08-21 16:36:07，"Timecollector" ***@***.***> 写道：

已经上传了，https://github.com/Timecollector/Grey_Model/blob/main/test.xlsx
