### ISSUE TITLE
关于gm1n预测结果的问题

### ISSUE THREAD

**Issue by chenph4** [Timecollector/Grey_Model#5]
楼主你好，我刚开始学习做python的灰色模型，请问下，你的GM1N模型最后的预测函数为空，这部分是需要自己填写吗？我做的是一个腐蚀模型，不太清楚这部分代码的内容，还请大佬解惑

**Comment by chenph4** [comment]
抱歉，没看到你更新的代码，直接下载了release的文件，解决了

**Comment by fiksdano** [comment]
> 抱歉，没看到你更新的代码，直接下载了release的文件，解决了

同学你好，我现在也遇到这个问题，请问你这个releaser文件是怎么下载的呢？我现在把结果打印出来，然后显示[1170.66, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
[nan, nan, nan]这样 的结果。

**Comment by chenph4** [comment]
> 

我不清楚你的输入数据是怎样的，我用作者更新后的文件是可以进行预测的，你看看预测步长是否满足要求？
